client_id = "0e4a73bd4e8c376d49369cf5d8600496"
name = "8W-COA"
application_url = "https://metaobject-paginator.vercel.app"
embedded = false

[app_proxy]
url = "/coas"
prefix = "apps"
subpath = "coas"

[webhooks]
api_version = "2025-10"
[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"
[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_metaobjects,read_products,read_files,write_app_proxy"

[auth]
redirect_urls = ["https://metaobject-paginator.vercel.app/auth/callback"]